### ISSUE TITLE
Tweaks to keywords #suggestion

### ISSUE THREAD

**Issue by chrismessina** [carlosgaldino/alfred-emoji-workflow#14]
I can never remember to type "symoji" so I replaced your keywords with ":" and "emoji"; the former pulls up the emoji codes, the latter the symbols. Helps me remember much better!

**Comment by maique** [comment]
I had a hard time too, so I just switched them and now use 'emoji' all the time. I have no use for 'symoji'.

**Comment by carlosgaldino** [comment]
Thanks, I just left a comment on the `README` with the suggestion.
