### ISSUE TITLE
Move symoji command into a subaction of emoji

### ISSUE THREAD

**Issue by lindskogen** [carlosgaldino/alfred-emoji-workflow#16]
Look at the command structure of: https://github.com/ruedap/alfred2-font-awesome-workflow/

**Comment by carlosgaldino** [comment]
I don't think this workflow has enough commands to require such interaction. Two separate commands are fine and less than typing `emoji sym [query]`.

Thanks for the idea, though.

**Comment by lindskogen** [comment]
The idea would be that you write `emoji query` then hold shift and press enter to get the symbol instead of the name of the symbol!

**Comment by carlosgaldino** [comment]
@lindskogen Ah ok. I saw the gif on the workflow you mentioned and thought you wanted a subcommand.

Since another person asked for the same thing on #17 I will leave that open to track the progress (if any).

Thanks.
