### ISSUE TITLE
Use modifier key to copy symbol of the selected emoji, instead of different keyword

### ISSUE THREAD

**Issue by tobscure** [carlosgaldino/alfred-emoji-workflow#17]
e.g. if you type "emoji +1" and press enter, `:+1:` is copied to your clipboard. But if you press Ctrl+Enter, 👍 is copied.

Rationale is that it's easier to just type "emoji" without having to think which version you want until you actually find the emoji you're looking for.

[This FontAwesome workflow](https://github.com/ruedap/alfred2-font-awesome-workflow) does this, and it's glorious.

**Comment by matrixagent** [comment]
That would be incredibly useful, two commands almost defeat the purpose of ease of use. I often find myself never using workflows that could be useful because their command structure wasn't planned well enough and I never get over the stage of "trying to remember the commands".

**Comment by iansinnott** [comment]
:+1: This would be a great improvement to an excellent workflow

**Comment by dewey** [comment]
Yes please! :fire:

**Comment by mckelvaney** [comment]
:+1:

**Comment by keithamus** [comment]
@tobscure @matrixagent @iansinnott @dewey @mckelvaney do you want to try out my PR (https://github.com/carlosgaldino/alfred-emoji-workflow/pull/22) and see if this is appropriate?
