### ISSUE TITLE
Support new emoji for OS X 10.11.1

### ISSUE THREAD

**Issue by semiosis** [carlosgaldino/alfred-emoji-workflow#18]
Add emoji from Unicode 7 (ios 8.3) & Unicode 8 (ios 9.1)

See [emojipedia](http://blog.emojipedia.org/ios-9-1-includes-new-emojis/) for details.

Thank you!

**Comment by gravicle** [comment]
+1

**Comment by klaas** [comment]
+1 This would be awesome!

**Comment by shanegriffiths** [comment]
:+1:  Want

**Comment by semiosis** [comment]
I've pushed a new branch to my fork with the new emoji... https://github.com/semiosis/alfred-emoji-workflow/tree/generate-emoji

Instead of manually adding all the symbols & related words I wrote a generator to produce them from the official emoji list from unicode.org.  One drawback of this strategy was that I had to remove the old symbols & related words lists because they did not use the same (official) emoji names.

Please let me know if you find this useful.

Thanks!

**Comment by semiosis** [comment]
I further improved my fork to include all the custom related words (and support future custom words) by generating a custom_related.json file with the extra words from related_words.rb.  Now it's easy to manage custom related words and merge them with the canonical annotations when future updates come out.

**Comment by semiosis** [comment]
https://github.com/carlosgaldino/alfred-emoji-workflow/pull/19

**Comment by chrismessina** [comment]
+1
