### ISSUE TITLE
Add support for new emoji

### ISSUE THREAD

**Issue by davidchiles** [carlosgaldino/alfred-emoji-workflow#21]
There are new emoji as of OSX 10.11.1 

http://www.engadget.com/2015/10/21/os-x-10-11-1-and-ios-9-1/

🌮🌮🌮

**Comment by sammarcus** [comment]
:pray:

**Comment by uribo** [comment]
:+1:

**Comment by maique** [comment]
If we just add the lines on https://github.com/carlosgaldino/alfred-emoji-workflow/blob/master/related_words.rb will the new ones show up ?  

What I mean is can we add 
`'robot_face' => ['robot', 'bot', 'droid'],`
and expect it to work ? Or is there something else you need to do ?

**Comment by gnestor** [comment]
@maique The new emojis would need to be added to emoji_symbols.rb and related_words.rb and their 64x64 images added to images...

**Comment by maique** [comment]
Cool, thanks. I'll try a couple and see how that goes. Really need a couple of them, so I'll start there. If everything works out fine I'll keep going.

**Comment by dvcrn** [comment]
Any updates on this? :)

**Comment by AeroEchelon** [comment]
+1

For those who need a quick shortcut to new emojis:

```
CTRL + CMD + SPACEBAR
```

**Comment by rmm5t** [comment]
Try https://github.com/jsumners/alfred-emoji as an alternative

**Comment by carlosgaldino** [comment]
This project is being archived.
