### ISSUE TITLE
Automatically paste (emoji symbols) to front-most app by default

### ISSUE THREAD

**Issue by wookayin** [carlosgaldino/alfred-emoji-workflow#27]
Hi 👏, thanks for an awesome workflow!

By default, the workflow's output action is just copying the actual emoji symbol into clipboard.

However, in my most usage cases (and possibly for others), when I trigger the workflow I just want to insert the emoji symbol directly into the front-most application. If it is done by default, we do not need to input an extra keystroke, say "cmd-V" (paste).

I see that changing this default behavior can be achieved extremely simply, as follows:

![image](https://cloud.githubusercontent.com/assets/1009873/13902877/5bcbc676-eea2-11e5-9ea1-2dd3e094e8fe.png)

How about enable this option by default? I would be happy to discuss on it.
Thanks.

**Comment by bryanvillarin** [comment]
Hey @wookayin,

> How about enable this option by default?

I _just_ found and installed this workflow in Alfred v2.8.5 (439), and saw that the option **Automatically paste to front most app** is enabled.

I can see that @carlosgaldino [added it on 2016-05-02](https://github.com/carlosgaldino/alfred-emoji-workflow/commit/2792b22abcad94a859b9e133cd43c05843197bde).

_P.S. Thank you, Carlos!_ 😃

**Comment by carlosgaldino** [comment]
Yes @bryanvillarin, you are correct. I enabled it and @wookayin if you download the latest version you will see that is now enabled by default. I'll close this one. Thank you!
