### ISSUE TITLE
THERE ARE NO TACOS!!! WTF

### ISSUE THREAD

**Issue by jeeftor** [carlosgaldino/alfred-emoji-workflow#32]
(I realize somebody called this out already but tacos are so important i think they need a separate issue)

**Comment by joshmedeski** [comment]
As a Texan I agree, I need the taco emoji in my life!

**Comment by rmm5t** [comment]
Try https://github.com/jsumners/alfred-emoji as an alternative

**Comment by jeeftor** [comment]
Oh yea. I ended up writing my own plugin with auto update capabilities. Pulls data directly from Unicode. https://github.com/jeeftor/EmojiTaco

**Comment by carlosgaldino** [comment]
This project is being archived.
