### ISSUE TITLE
Cannot copy some emojis to clipboard

### ISSUE THREAD

**Issue by zhuravel** [carlosgaldino/alfred-emoji-workflow#33]
![backstop menubar 2016-11-10 12-52-25](https://cloud.githubusercontent.com/assets/1140581/20174100/f9460a6e-a744-11e6-9599-db77cbe7bf4f.png)

**Comment by jsumners** [comment]
The `:metal:` emoji also doesn't copy to the clipboard.

**Comment by carlosgaldino** [comment]
This project is being archived.
