### ISSUE TITLE
Opt out of output the emoji on copy

### ISSUE THREAD

**Issue by guywaldman** [carlosgaldino/alfred-emoji-workflow#37]
Great workflow, thanks for much for this! 🎉

I'm not sure whether this is desired behavior, but try putting your cursor on some input and using the workflow to copy an emoji -- it'll get outputted.

I would love for the option to opt out of this behavior, meaning only copying the emoji. Or maybe make this configurable?

Thanks again!

**Comment by carlosgaldino** [comment]
This project is being archived.
