### ISSUE TITLE
Heart Emoji not an Emoji

### ISSUE THREAD

**Issue by lavoy** [carlosgaldino/alfred-emoji-workflow#9]
Looks like the :heart: symbol is actually the ❤ symbol. Can we make it the emoji heart?

![screen shot 2015-01-26 at 12 05 11 pm](https://cloud.githubusercontent.com/assets/314876/5905164/b6b774e8-a553-11e4-944c-d5d1ed1efb35.png)

**Comment by carlosgaldino** [comment]
I updated some of the symbols on 9e3f18f8060476d1bca19cc48579fc359a36632e, this was one of them.

Thank you.
